version: '3'
services:
  django:
    build:
      context: ./book_app
    ports:
      - 8000:8000
    volumes:
      - ./book_app:/app
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb://mongodb:27017/dev

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
