"""
Django settings for book_app project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#rir(3@r^5*t6w94ino3l%#+d*ro6-@s+(1$l1vl@uqg_fm)nu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_mongoengine',
    "book_app",
    'corsheaders',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'book_app.exception_handlers.custom_exception_handler',
}

ROOT_URLCONF = "book_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "book_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASE_ROUTERS = ['book_app.dbrouter.DBRouter']

# Make sure the data folder exists
DATA_DIR = BASE_DIR / 'data'
DATA_DIR.mkdir(parents=True, exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    },
    'documents': {
        'HOST': os.environ.get(
            'MONGODB_HOST',
            'mongodb://localhost:27017/dev',
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# NOTE(pagarsky): Yes, you're not supposed to store credentials in the code
# but I couldn't be bothered to do this properly
TRANSLATOR_CREDENTIALS = {
  "apikey": "gZZR6o1yDPeEZhaeBb--7wOhFC7VySxJw2h5jT7wVldz",
  "iam_apikey_description": "Auto-generated for key crn:v1:bluemix:public:language-translator:eu-de:a/36e48a490db341a8ba7f59b12b5878fb:abf40bcf-a897-4f79-a46c-1c28f289b287:resource-key:213d7d64-a6d3-4bfc-8650-3d9b5bcc0b74",
  "iam_apikey_id": "ApiKey-61420660-4cb9-4cb1-bdce-4dd02d024089",
  "iam_apikey_name": "Auto-generated service credentials",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/36e48a490db341a8ba7f59b12b5878fb::serviceid:ServiceId-1be78992-2af5-4ecd-a0b5-04e007324b24",
  "url": "https://api.eu-de.language-translator.watson.cloud.ibm.com/instances/abf40bcf-a897-4f79-a46c-1c28f289b287"
}

TTS_CREDENTIALS = {
  "apikey": "COWTk4QPudlKDbDllodou-W-V5DRQ2iCgVN_RaAb02FD",
  "iam_apikey_description": "Auto-generated for key crn:v1:bluemix:public:text-to-speech:eu-de:a/36e48a490db341a8ba7f59b12b5878fb:fa87251c-f2d0-49bf-a915-d9a91e7ebfb7:resource-key:c272f0b0-055c-41f7-a190-12df68aec25b",
  "iam_apikey_id": "ApiKey-eff3a87e-9cdc-4138-a89d-4a243665fb90",
  "iam_apikey_name": "Auto-generated service credentials",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/36e48a490db341a8ba7f59b12b5878fb::serviceid:ServiceId-61e1005b-7cc3-4ef4-b740-63611ad025f4",
  "url": "https://api.eu-de.text-to-speech.watson.cloud.ibm.com/instances/fa87251c-f2d0-49bf-a915-d9a91e7ebfb7"
}
