# Generated by Django 5.0.4 on 2024-04-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='profile',
            table_comment='default',
        ),
    ]
